Fix sample app crashing at startup due to missing aboutlibraries.json.
+ Crash:

  java.lang.IllegalStateException: Please provide the required library data via the available APIs.
  Depending on the platform this can be done for example via `Libs.Builder().withJson()`.
  For Android there exists an `Libs.Builder().withContext(context).build()`, automatically loading the `aboutlibraries.json` file from   the `raw` resources folder.
  When using compose or other parent modules, please check their corresponding APIs.
    at com.mikepenz.aboutlibraries.Libs$Builder.build(Libs.kt:44)
    at com.mikepenz.markdown.MainActivity.onCreate$lambda$0(MainActivity.kt:17)
    ...